# Generated by Django 3.2 on 2022-12-14 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='deleted_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date deleted'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='founder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_founder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organization',
            name='industry',
            field=models.ManyToManyField(related_name='organization_industry', to='organization.Industry'),
        ),
    ]
