# Generated by Django 3.2 on 2022-12-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20221214_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='area_served',
            field=models.CharField(blank=True, choices=[('WW', 'world wide'), ('NW', 'national wide'), ('SW', 'state wide')], default='SW', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_type',
            field=models.CharField(blank=True, choices=[('PRIVATE', 'private'), ('PUBLIC', 'public'), ('GOVERNMENT', 'government'), ('FOREIGN', 'foreign'), ('CHARITABLE', 'charitable'), ('SHARE', 'shared'), ('ONE_OWNER', 'one owner')], default='PRIVATE', max_length=50, null=True),
        ),
    ]
