# Generated by Django 3.2 on 2022-12-14 11:58

from django.db import migrations
import modules.contrib.ckeditor_uploader.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20221214_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=modules.contrib.ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
