# Generated by Django 3.2 on 2023-01-03 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='author',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='author',
        ),
    ]
