# Generated by Django 3.2 on 2022-12-17 06:27

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.AddField(
            model_name='product',
            name='iso_verification',
            field=django_fsm.FSMIntegerField(choices=[(0, 'draft'), (1, 'verified'), (2, 'rejected')], default=0, max_length=1),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
